import { Decoration, EditorView, MatchDecorator, ViewPlugin } from "@codemirror/view";
import type { DecorationSet, ViewUpdate } from "@codemirror/view";
import { RangeSetBuilder } from "@codemirror/state";
import type { PluginConfig } from "../../config/types";
import { DEFAULT_SETTINGS } from "../../config/defaults";

const HIGHLIGHT_CLASS = "cm-quran-key-text";
const MARKDOWN_BLOCK_CLASS = "quran-key-text-block";
const ORNATE_NUMBER_CLASS = "quran-key-ornate-number";
const AYAH_NOTE_LINK_CLASS = "quran-key-ayah-note-link";
const LAZY_AYAH_CLASS = "quran-key-lazy-ayah";
const REFLECTION_BLOCK_ID_CLASS = "cm-quran-key-reflection-id";
const LIST_ITEM_CLASS = "cm-quran-key-list-item";
const ARABIC_INDIC_DIGITS = "\u0660-\u0669";

function escapeRegex(literal: string): string {
	return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function toAsciiDigits(value: string): string {
	return value
		.replace(/[٠-٩]/g, (digit) => String("٠١٢٣٤٥٦٧٨٩".indexOf(digit)))
		.replace(/[۰-۹]/g, (digit) => String("۰۱۲۳۴۵۶۷۸۹".indexOf(digit)));
}

function portableAyahMarker(value: string): string | null {
	const digits = value.match(/[٠-٩۰-۹]+/);
	return digits ? `(${toAsciiDigits(digits[0])})` : null;
}

/** Converts only Quran content while it is being copied. The document keeps
 * its original wikilinks and configured marker style; the clipboard receives
 * a portable `(1)`-style marker instead. */
export function formatPortableAyahClipboardText(text: string, wrapperStart: string, wrapperEnd: string): string {
	const wrapperPattern = new RegExp(`${escapeRegex(wrapperStart)}[\\s\\S]*?${escapeRegex(wrapperEnd)}`, "g");
	const wikilinkPattern = /\[\[([^\]\n|]+)\|([^\]\n]+)\]\]/g;
	const markerPattern = /^(?:۝)?[()٠-٩۰-۹]+$/;

	return text.replace(wrapperPattern, (block) => {
		let portable = block.replace(wikilinkPattern, (full, _target: string, alias: string) => {
			if (!markerPattern.test(alias.trim())) return full;
			return portableAyahMarker(alias.trim()) ?? alias;
		});

		const markerBeforeEnd = new RegExp(`(?:۝)?(?:[٠-٩۰-۹]+|\\([٠-٩۰-۹]+\\))(?=\\s*${escapeRegex(wrapperEnd)})`);
		portable = portable.replace(markerBeforeEnd, (marker) => portableAyahMarker(marker) ?? marker);
		return portable;
	});
}

function escapeHtml(value: string): string {
	return value.replace(/[&<>"']/g, (character) => ({
		"&": "&amp;",
		"<": "&lt;",
		">": "&gt;",
		'"': "&quot;",
		"'": "&#39;",
	}[character] ?? character));
}

export function createQuranHighlightExtension(wrapperStart: string, wrapperEnd: string) {
	const pattern = new RegExp(`${escapeRegex(wrapperStart)}.*?${escapeRegex(wrapperEnd)}`, "g");
	const decorator = new MatchDecorator({
		regexp: pattern,
		decoration: Decoration.mark({ class: HIGHLIGHT_CLASS }),
	});

	return ViewPlugin.fromClass(
		class {
			decorations: DecorationSet;
			constructor(view: EditorView) {
				this.decorations = decorator.createDeco(view);
			}
			update(update: ViewUpdate) {
				this.decorations = decorator.updateDeco(update, this.decorations);
			}
		},
		{ decorations: (v) => v.decorations }
	);
}

export function createOrnateNumberHighlightExtension() {
	const pattern = new RegExp(`[${ARABIC_INDIC_DIGITS}]+`, "g");
	const decorator = new MatchDecorator({
		regexp: pattern,
		decoration: Decoration.mark({ class: ORNATE_NUMBER_CLASS }),
	});

	return ViewPlugin.fromClass(
		class {
			decorations: DecorationSet;
			constructor(view: EditorView) {
				this.decorations = decorator.createDeco(view);
			}
			update(update: ViewUpdate) {
				this.decorations = decorator.updateDeco(update, this.decorations);
			}
		},
		{ decorations: (v) => v.decorations }
	);
}

/** Obsidian can expose block IDs in Live Preview. Mark only IDs generated by
 * Quran Key so CSS can hide them there while leaving Source mode inspectable. */
export function createReflectionBlockIdExtension() {
	const decorator = new MatchDecorator({
		regexp: /\s+\^qk-reflection-[a-z0-9]+/gi,
		decoration: Decoration.mark({ class: REFLECTION_BLOCK_ID_CLASS }),
	});

	return ViewPlugin.fromClass(
		class {
			decorations: DecorationSet;
			constructor(view: EditorView) {
				this.decorations = decorator.createDeco(view);
			}
			update(update: ViewUpdate) {
				this.decorations = decorator.updateDeco(update, this.decorations);
			}
		},
		{ decorations: (v) => v.decorations }
	);
}

/** Keep generated ayah links intact while hiding only their target syntax in
 * the editor. The visible alias (for example `١١`) remains in place, so the
 * link stays navigable without exposing `[[note-title|...]]` as cursor clutter. */
export function createAyahWikilinkSyntaxExtension() {
	const hidden = Decoration.replace({});
	const wikilinkPattern = /\[\[([^\]\n|]+)\|([^\]\n]+)\]\]/g;
	const markerPattern = /^[()۝٠-٩۰-۹]+$/;

	const buildDecorations = (view: EditorView): DecorationSet => {
		const builder = new RangeSetBuilder<Decoration>();
		let lineOffset = 0;
		for (const line of view.state.doc.iterLines()) {
			wikilinkPattern.lastIndex = 0;
			let match: RegExpExecArray | null;
			while ((match = wikilinkPattern.exec(line)) !== null) {
				if (!markerPattern.test(match[2])) continue;
				const absoluteStart = lineOffset + match.index;
				const aliasStart = absoluteStart + match[0].indexOf("|") + 1;
				const closingStart = absoluteStart + match[0].length - 2;
				builder.add(absoluteStart, aliasStart, hidden);
				builder.add(closingStart, absoluteStart + match[0].length, hidden);
			}
			lineOffset += line.length + 1;
		}
		return builder.finish();
	};

	const plugin = ViewPlugin.fromClass(
		class {
			decorations: DecorationSet;
			constructor(view: EditorView) {
				this.decorations = buildDecorations(view);
			}
			update(update: ViewUpdate) {
				if (update.docChanged) this.decorations = buildDecorations(update.view);
			}
		},
		{
			decorations: (value) => value.decorations,
			provide: (plugin) => EditorView.atomicRanges.of((view) => view.plugin(plugin)?.decorations ?? Decoration.none),
		}
	);
	return plugin;
}

/** Ensures Ctrl/Cmd+C copies visible Quran text rather than the hidden
 * wikilink source. Rich-text destinations receive the same portable text,
 * without a link element that could reintroduce the target syntax. */
export function createAyahWikilinkClipboardExtension(wrapperStart: string, wrapperEnd: string) {
	return EditorView.domEventHandlers({
		copy(event, view) {
			const ranges = view.state.selection.ranges.filter((range) => !range.empty);
			if (ranges.length === 0 || !event.clipboardData) return false;

			const selected = ranges.map((range) => view.state.sliceDoc(range.from, range.to)).join("\n");
			const portable = formatPortableAyahClipboardText(selected, wrapperStart, wrapperEnd);
			event.clipboardData.setData("text/plain", portable);
			event.clipboardData.setData("text/html", `<div dir="rtl">${escapeHtml(portable).replace(/\n/g, "<br>")}</div>`);
			event.preventDefault();
			return true;
		},
	});
}

/** Gives list items containing Quran text a stable formatting boundary in
 * Live Preview. Without it, Markdown's list tokens can win the inline font
 * and line-height cascade even though the same quote renders correctly in a
 * paragraph. */
export function createQuranListFormattingExtension(wrapperStart: string, wrapperEnd: string) {
	const lineDecoration = Decoration.line({ class: LIST_ITEM_CLASS });
	const listPrefix = /^\s*(?:[-+*]|\d+[.)])\s+/;
	const buildDecorations = (view: EditorView): DecorationSet => {
		const builder = new RangeSetBuilder<Decoration>();
		let lineOffset = 0;
		for (const line of view.state.doc.iterLines()) {
			if (listPrefix.test(line) && line.includes(wrapperStart) && line.includes(wrapperEnd)) {
				builder.add(lineOffset, lineOffset, lineDecoration);
			}
			lineOffset += line.length + 1;
		}
		return builder.finish();
	};

	return ViewPlugin.fromClass(
		class {
			decorations: DecorationSet;
			constructor(view: EditorView) {
				this.decorations = buildDecorations(view);
			}
			update(update: ViewUpdate) {
				if (update.docChanged) this.decorations = buildDecorations(update.view);
			}
		},
		{ decorations: (value) => value.decorations }
	);
}

export function createOrnateNumberPostProcessor(): (el: HTMLElement) => void {
	const pattern = new RegExp(`[${ARABIC_INDIC_DIGITS}]+`, "g");

	function walk(node: Node): void {
		if (node.nodeType === Node.TEXT_NODE) {
			const text = node.nodeValue || "";
			pattern.lastIndex = 0;
			if (pattern.test(text)) {
				pattern.lastIndex = 0;
				const frag = createFragment();
				let lastIndex = 0;
				let m: RegExpExecArray | null;
				while ((m = pattern.exec(text)) !== null) {
					if (m.index > lastIndex) {
						frag.appendText(text.slice(lastIndex, m.index));
					}
					frag.createSpan({ cls: ORNATE_NUMBER_CLASS, text: m[0] });
					lastIndex = m.index + m[0].length;
				}
				if (lastIndex < text.length) {
					frag.appendText(text.slice(lastIndex));
				}
				node.parentNode?.replaceChild(frag, node);
			}
		} else {
			const children = Array.from(node.childNodes);
			for (const child of children) walk(child);
		}
	}

	return walk;
}

export function createMarkdownPostProcessor(wrapperStart: string, wrapperEnd: string): (el: HTMLElement) => void {
	const pattern = new RegExp(`${escapeRegex(wrapperStart)}(.*?)${escapeRegex(wrapperEnd)}`, "g");

	function walk(node: Node): void {
		if (node.nodeType === Node.TEXT_NODE) {
			const text = node.nodeValue || "";
			if (text.includes(wrapperStart) && text.includes(wrapperEnd)) {
				const frag = createFragment();
				let lastIndex = 0;
				let m: RegExpExecArray | null;
				while ((m = pattern.exec(text)) !== null) {
					if (m.index > lastIndex) {
						frag.appendText(text.slice(lastIndex, m.index));
					}
					frag.createSpan({ cls: HIGHLIGHT_CLASS, text: `${wrapperStart}${m[1]}${wrapperEnd}` });
					lastIndex = m.index + m[0].length;
				}
				if (lastIndex < text.length) {
					frag.appendText(text.slice(lastIndex));
				}
				node.parentNode?.replaceChild(frag, node);
			}
		} else {
			const children = Array.from(node.childNodes);
			for (const child of children) walk(child);
		}
	}

	return (el: HTMLElement) => {
		walk(el);
		// A wikilink around the ayah marker splits the Quran text into several
		// DOM nodes, so the text-node walker above cannot see both wrapper
		// glyphs. Mark the containing block as a fallback styling boundary.
		for (const block of Array.from(el.querySelectorAll("p, li, blockquote"))) {
			const text = block.textContent ?? "";
			if (text.includes(wrapperStart) && text.includes(wrapperEnd)) block.classList.add(MARKDOWN_BLOCK_CLASS);
		}
		for (const link of Array.from(el.querySelectorAll("a.internal-link"))) {
			const label = link.textContent?.trim() ?? "";
			if (/^[()۝\u0660-\u0669\u06F0-\u06F9]+$/.test(label)) link.classList.add(AYAH_NOTE_LINK_CLASS);
		}
	};
}

export function createLazyAyahMarkerPostProcessor(
	openAyahNote: (surahId: number, ayahId: number) => Promise<void>,
	surahId: number
): (el: HTMLElement) => void {
	return (el) => {
		if (!Number.isInteger(surahId)) return;
		const quranBlocks = Array.from(el.querySelectorAll<HTMLElement>(`.${HIGHLIGHT_CLASS}`));
		const markerPattern = /[٠-٩]+/g;
		for (const block of quranBlocks) {
			decorateLazyMarkers(block, surahId, markerPattern, openAyahNote);
		}
	};
}

function decorateLazyMarkers(
	root: HTMLElement,
	 surahId: number,
	pattern: RegExp,
	openAyahNote: (surahId: number, ayahId: number) => Promise<void>
): void {
	const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
	const textNodes: Text[] = [];
	let current: Node | null;
	while ((current = walker.nextNode())) {
		if (current.parentElement?.closest(`.${LAZY_AYAH_CLASS}, a.internal-link`)) continue;
		textNodes.push(current as Text);
	}

	for (const textNode of textNodes) {
		const text = textNode.nodeValue ?? "";
		pattern.lastIndex = 0;
		if (!pattern.test(text)) continue;
		pattern.lastIndex = 0;
		const fragment = createFragment();
		let lastIndex = 0;
		let match: RegExpExecArray | null;
		while ((match = pattern.exec(text)) !== null) {
			if (match.index > lastIndex) fragment.appendChild(document.createTextNode(text.slice(lastIndex, match.index)));
			const marker = createSpan();
			marker.classList.add(LAZY_AYAH_CLASS);
			marker.dataset.quranKeySurah = String(surahId);
			marker.dataset.quranKeyAyah = String(arabicIndicToNumber(match[0]));
			marker.textContent = match[0];
			marker.setAttribute("role", "button");
			marker.setAttribute("tabindex", "0");
			marker.setAttribute("aria-label", `Open ayah note ${surahId}:${marker.dataset.quranKeyAyah}`);
			const open = () => void openAyahNote(surahId, Number(marker.dataset.quranKeyAyah)).catch(() => undefined);
			marker.addEventListener("click", open);
			marker.addEventListener("keydown", (event: KeyboardEvent) => {
				if (event.key === "Enter" || event.key === " ") {
					event.preventDefault();
					open();
				}
			});
			fragment.appendChild(marker);
			lastIndex = match.index + match[0].length;
		}
		if (lastIndex < text.length) fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
		textNode.parentNode?.replaceChild(fragment, textNode);
	}
}

function arabicIndicToNumber(value: string): number {
	return Number(value.replace(/[٠-٩]/g, (digit) => String("٠١٢٣٤٥٦٧٨٩".indexOf(digit))));
}

export function applyStyleVariables(settings: PluginConfig): void {
	const fontFamily = "'QPC Hafs v18', serif";
	const fontSize = settings.quranFontSize || DEFAULT_SETTINGS.quranFontSize;
	const lineHeight = settings.quranLineHeight || DEFAULT_SETTINGS.quranLineHeight;

	document.body.style.setProperty("--quran-key-font-family", fontFamily);
	document.body.style.setProperty("--quran-key-font-size", `${fontSize}em`);
	document.body.style.setProperty("--quran-key-line-height", String(lineHeight));
	document.body.style.setProperty("--quran-key-line-height-loose", String(lineHeight + 0.4));
	const legacyColor = settings.quranColor || DEFAULT_SETTINGS.quranColor;
	document.body.style.setProperty("--quran-key-color-dark", settings.quranColorDark || legacyColor);
	document.body.style.setProperty("--quran-key-color-light", settings.quranColorLight || legacyColor);
}

export function cleanupStyleVariables(): void {
	document.body.style.removeProperty("--quran-key-font-family");
	document.body.style.removeProperty("--quran-key-font-size");
	document.body.style.removeProperty("--quran-key-line-height");
	document.body.style.removeProperty("--quran-key-line-height-loose");
	document.body.style.removeProperty("--quran-key-color-dark");
	document.body.style.removeProperty("--quran-key-color-light");
}
